name: Snake

on:
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Commit and push if changed
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"
          git add dist/github-contribution-grid-snake.svg
          git diff-index --quiet HEAD || git commit -m "Update contribution graph" && git push
